# This playbook is to be used to generate interface configuration (loopback0, loopback1, Ethernet) for the leafs and spines from underlay.yml

---
# For hosts: refer to the inventory file for an appropriate entry that would encompass DC2's leafs and spines
- hosts: all
  gather_facts: no
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/underlay.yml"
      name: underlay
  - name: Create template
    template:
      src: "{{lookup('env','PWD')}}/templates/interfaces.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_interface.cfg"
# Use the eos_config module to create a task to upload the configuration you created to the switch
  - name: Upload config
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_interface.cfg"


      
